name: docker containres
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Code
        uses: actions/checkout@v3
    #   - name: Install Node
    #     uses: actions/setup-node@v3
    #     with:
    #         node-version: 20
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
